name: Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    container: kivy/buildozer:latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
      run: |
          chmod -R 777 .
          echo "y" | buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: bin/*.apk
